// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vlfjvnsmlwzsmqvxhmff.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZsZmp2bnNtbHd6c21xdnhobWZmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5OTU4NDAsImV4cCI6MjA2NTU3MTg0MH0.H5tNxOsuWqbY9sdd5N2CG9UqMnpLuh8eaLc3qDl2mZo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);